maximum_length_title_category: 250
maximum_length_content_word: 200
per_page: 5
quanlity_question: 5
per_page_words: 10
per_page_activities: 15
answer_count: 0
csv: "csv"
xls: "xls"
filter_words:
  learned: "learned"
  learned_correct: "learned_correct"
  learned_not_correct: "learned_not_correct"
  not_learned: "not_learned"
  get_all: "get_all"
